#!/usr/bin/env bash

function kill_prev() {
    # pgrep returns pid
    # $0 returns current script name
    # $$ contains current pid (grep ignore so it doesn't suicide)
    kill $(pgrep -f "$0" | grep -v $$) >/dev/null 2>&1
}

function validate_input() {
    local IFS=$'/\n'
    local opts
    local fl

    cd "${wallpapers_dir}" || exit
    opts=( $(ls -1 -d -- */) )
    fl=0

    for i in "${opts[@]}"
    do
        if [ "$1" = "$i" ]; then
            fl=1
            group=$1
        fi
    done

    if [ $fl -eq 0 ]; then
        echo "$1 not found"
        echo "Available params:"
        echo "${opts[@]}"
        exit 1
    fi
}

function change_hyprpaper() {
    eval hyprctl hyprpaper unload all >/dev/null 2>&1
    eval hyprctl hyprpaper preload "$1" >/dev/null 2>&1
    eval hyprctl hyprpaper wallpaper ",$1" >/dev/null 2>&1
}

function change_gnome_wallpaper() {
    eval gsettings set org.gnome.desktop.background picture-uri-dark "$1"
}

function change_wallpaper() {
    local IFS=$'/\n'
    local ptf
    local wallpapers
    local len
    local idx

    ptf="$wallpapers_dir/$group"
    wallpapers=( $(ls "$ptf") )

    idx=0
    len=${#wallpapers[@]}

    while true
    do
        sleep 1m
        # randomly choose a wallpaper
        idx=$((RANDOM % len))

        # actually setting the wallpaper
        # change_gnome_wallpaper "$ptf/${wallpapers[idx]}"
        change_hyprpaper "$ptf/${wallpapers[idx]}"
    done
}

function main() {
    local wallpapers_dir
    local group
    wallpapers_dir="${HOME}/.wallpapers"
    validate_input "$@"
    kill_prev
    change_wallpaper & disown
}

main "$@"
