#!/usr/bin/env bash

function input-validation() {
    if [[ $# -ne 1 ]]; then
        echo "Only one argument is required, on or off"
        exit 1
    elif [[ $1 != "on" ]] && [[ $1 != "off" ]]; then
        echo "Only one argument is required, on or off"
        exit 1
    fi
}

function game-on() {
    sudo i8kctl fan1 2
    sudo i8kctl fan3 2
    sudo systemctl stop keyboard-mapping.service
    battery-monitor -k
    ~/.local/python/ty-plug -s on
}

function game-off() {
    sudo i8kctl fan1 0
    sudo i8kctl fan3 1
    sudo systemctl start keyboard-mapping.service
    battery-monitor -q --min=64 --max=67
    ~/.local/python/ty-plug -s off
}

function main() {
    input-validation "$@"
    sudo echo "" || exit 1
    if [[ $1 == "on" ]]; then
        game-on
    else
        game-off
    fi
}

main "$@"
