#!/usr/bin/env bash

function select-dir() {
    local dirs=(
        "$HOME/Projects/work"
        "$HOME/Projects/personal"
    )

    if [[ $# -eq 0 ]]; then
        selected=$(find "${dirs[@]}" -mindepth 1 -maxdepth 2 -type d | fzf)
    elif [[ $# -eq 1 ]]; then
        selected=$1
    else
        echo "Invalid number of arguements"
        exit 1
    fi

    if [[ -z $selected ]]; then
        echo "Must select a directory"
        exit 1
    fi
}

function open-tmux() {
    selected_name=$(basename "$selected" | tr .: _)

    if ! tmux has-session -t="$selected_name" 2>/dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi

    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$selected_name"
    else
        tmux switch-client -t "$selected_name"
    fi
}

function main() {
    local selected
    local selected_name
    select-dir "$@"
    open-tmux
}

main "$@"
