#!/usr/bin/env bash

function select_dir() {
    local dirs=(
        "$HOME/Projects/work"
        "$HOME/Projects/personal"
    )

    if [[ $# -eq 1 ]]; then
        selected=$1
    else
        selected=$(find "${dirs[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)
        echo "$selected"
    fi

    if [[ -z $selected ]]; then
        echo "not selected anything"
        exit 0
    fi
}

function open_tmux() {
    selected_name=$(basename "$selected" | tr . _)

    if [[ -z $TMUX ]]; then
        tmux new-session -As "$selected_name" -c "$selected"
        exit 0
    fi

    if ! tmux has-session -t="$selected_name" 2> /dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi

    tmux switch-client -t "$selected_name"
}

function main() {
    local selected
    local selected_name
    select_dir "$@"
    open_tmux
}

main "$@"
