"$schema" = "https://starship.rs/config-schema.json"

format = """[](bold gray) $directory$git_branch$git_status $fill $all"""
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[username]
format = "[$user]($style) "

[directory]
truncation_length = 4
truncation_symbol = "../"

[fill]
symbol = " "

[cmd_duration]
min_time = 500
format = "[$duration]($style)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = "$all_status$ahead_behind"
conflicted = "[=](bold red)"
untracked = "[?$count](blue) "
stashed = "[\\$$count](gray) "
modified = "[!$count](yellow) "
staged = "[+$count](yellow) "
renamed = "[»$count](yellow) "
deleted = "[x$count](yellow) "
ahead = "[⇡$count](green) "
diverged = "[⇡$ahead_count⇣$behind_count](gray) "
behind = "[⇣$count](green) "
ignore_submodules = true

[nodejs]
symbol = "󰎙 "
format = "[$symbol$version]($style) "

[rust]
symbol = "󱘗 "
format = "[$symbol($version)]($style) "

[c]
detect_extensions = [
    "c",   # Standard C source file
    "h",   # Headers (shared with C)
    "cpp", # Standard C++ source files
    "cc",  # Alternate C++ source files
    "cxx", # Alternate C++ source files
    "C",   # Uppercase C for C++ on case-sensitive systems
    "hpp", # Preferred C++ headers
    "hh",  # Alternate C++ headers
    "hxx", # Rare C++ headers
    "tpp", # Templates
    "tpl", # Template files
    "inl", # Inline files
    "ipp", # Template implementation files
]
format = "[$symbol($version(-$name))]($style) "
symbol = " "
